### ISSUE TITLE
errors compiling

### ISSUE THREAD

**Issue by ghost** [yunwilliamyu/opal#1]
Hi 

I am trying to install opal on Mac OSX system and ran into the following errors:

file.c:59:2: error: non-void function '_gdl_runtime_fread_rng' should return a value [-Wreturn-type]
        GDL_FREAD_STATUS (status, 1);
        ^
../gdl/gdl_errno.h:162:7: note: expanded from macro 'GDL_FREAD_STATUS'
    { GDL_ERROR_VOID ("fread failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:61:2: error: non-void function '_gdl_runtime_fread_rng' should return a value [-Wreturn-type]
        GDL_FREAD_STATUS (rng!=0, 1);
        ^
../gdl/gdl_errno.h:162:7: note: expanded from macro 'GDL_FREAD_STATUS'
    { GDL_ERROR_VOID ("fread failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:83:2: error: non-void function '_gdl_runtime_fwrite_rng' should return a value [-Wreturn-type]
        GDL_FWRITE_STATUS (status, 1);
        ^
../gdl/gdl_errno.h:167:7: note: expanded from macro 'GDL_FWRITE_STATUS'
    { GDL_ERROR_VOID ("fwrite failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:85:2: error: non-void function '_gdl_runtime_fwrite_rng' should return a value [-Wreturn-type]
        GDL_FREAD_STATUS (status, GDL_SUCCESS);
        ^
../gdl/gdl_errno.h:162:7: note: expanded from macro 'GDL_FREAD_STATUS'
    { GDL_ERROR_VOID ("fread failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:100:3: error: non-void function 'gdl_runtime_fread' should return a value [-Wreturn-type]
                GDL_FREAD_STATUS (T!=0, 1);
                ^
../gdl/gdl_errno.h:162:7: note: expanded from macro 'GDL_FREAD_STATUS'
    { GDL_ERROR_VOID ("fread failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:105:3: error: non-void function 'gdl_runtime_fread' should return a value [-Wreturn-type]
                GDL_FREAD_STATUS (run->rng!=0, 1);
                ^
../gdl/gdl_errno.h:162:7: note: expanded from macro 'GDL_FREAD_STATUS'
    { GDL_ERROR_VOID ("fread failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:120:3: error: non-void function 'gdl_runtime_fwrite' should return a value [-Wreturn-type]
                GDL_FWRITE_STATUS (status, GDL_SUCCESS);
                ^
../gdl/gdl_errno.h:167:7: note: expanded from macro 'GDL_FWRITE_STATUS'
    { GDL_ERROR_VOID ("fwrite failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:122:3: error: non-void function 'gdl_runtime_fwrite' should return a value [-Wreturn-type]
                GDL_FWRITE_STATUS (status, GDL_SUCCESS);
                ^
../gdl/gdl_errno.h:167:7: note: expanded from macro 'GDL_FWRITE_STATUS'
    { GDL_ERROR_VOID ("fwrite failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
8 errors generated.
make[2]: *** [file.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Making install in gdl
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in err
make[2]: Nothing to be done for `install-exec-am'.
 .././install-sh -c -d '/Users/ksoh/Projects/opal/util/ext/gdl-1.1/GDL/include/gdl'
 /usr/bin/install -c -m 644 gdl_errno.h gdl_message.h '/Users/ksoh/Projects/opal/util/ext/gdl-1.1/GDL/include/gdl'
Making install in run
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I..    -g -O2 -c -o file.lo file.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I.. -g -O2 -c file.c  -fno-common -DPIC -o .libs/file.o
file.c:59:2: error: non-void function '_gdl_runtime_fread_rng' should return a value [-Wreturn-type]
        GDL_FREAD_STATUS (status, 1);
        ^
../gdl/gdl_errno.h:162:7: note: expanded from macro 'GDL_FREAD_STATUS'
    { GDL_ERROR_VOID ("fread failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:61:2: error: non-void function '_gdl_runtime_fread_rng' should return a value [-Wreturn-type]
        GDL_FREAD_STATUS (rng!=0, 1);
        ^
../gdl/gdl_errno.h:162:7: note: expanded from macro 'GDL_FREAD_STATUS'
    { GDL_ERROR_VOID ("fread failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:83:2: error: non-void function '_gdl_runtime_fwrite_rng' should return a value [-Wreturn-type]
        GDL_FWRITE_STATUS (status, 1);
        ^
../gdl/gdl_errno.h:167:7: note: expanded from macro 'GDL_FWRITE_STATUS'
    { GDL_ERROR_VOID ("fwrite failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:85:2: error: non-void function '_gdl_runtime_fwrite_rng' should return a value [-Wreturn-type]
        GDL_FREAD_STATUS (status, GDL_SUCCESS);
        ^
../gdl/gdl_errno.h:162:7: note: expanded from macro 'GDL_FREAD_STATUS'
    { GDL_ERROR_VOID ("fread failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:100:3: error: non-void function 'gdl_runtime_fread' should return a value [-Wreturn-type]
                GDL_FREAD_STATUS (T!=0, 1);
                ^
../gdl/gdl_errno.h:162:7: note: expanded from macro 'GDL_FREAD_STATUS'
    { GDL_ERROR_VOID ("fread failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:105:3: error: non-void function 'gdl_runtime_fread' should return a value [-Wreturn-type]
                GDL_FREAD_STATUS (run->rng!=0, 1);
                ^
../gdl/gdl_errno.h:162:7: note: expanded from macro 'GDL_FREAD_STATUS'
    { GDL_ERROR_VOID ("fread failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:120:3: error: non-void function 'gdl_runtime_fwrite' should return a value [-Wreturn-type]
                GDL_FWRITE_STATUS (status, GDL_SUCCESS);
                ^
../gdl/gdl_errno.h:167:7: note: expanded from macro 'GDL_FWRITE_STATUS'
    { GDL_ERROR_VOID ("fwrite failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
file.c:122:3: error: non-void function 'gdl_runtime_fwrite' should return a value [-Wreturn-type]
                GDL_FWRITE_STATUS (status, GDL_SUCCESS);
                ^
../gdl/gdl_errno.h:167:7: note: expanded from macro 'GDL_FWRITE_STATUS'
    { GDL_ERROR_VOID ("fwrite failed", GDL_EFAILED);}
      ^
../gdl/gdl_errno.h:131:8: note: expanded from macro 'GDL_ERROR_VOID'
       return ; \
       ^
8 errors generated.
make[1]: *** [file.lo] Error 1
make: *** [install-recursive] Error 1
gcc -O2 -Wall -Wshadow -I./ -Iext/gdl-1.1/GDL/include -c drawfrag.c
drawfrag.c:18:10: fatal error: 'gdl/gdl_common.h' file not found
#include <gdl/gdl_common.h>
         ^
1 error generated.
make: *** [drawfrag.o] Error 1

Any advice on resolving these errors? Thank you.

**Comment by yunwilliamyu** [comment]
Unfortunately, I do not have access to a Mac, so that is not a supported OS. Also, that part of the code was forked from http://projects.cbio.mines-paristech.fr/largescalemetagenomics/
Does their code work for you? If not, then the problem is upstream of what we've written.

There seems like some kind of path error in the environment. The install script should autoconfigure the correct paths for GCC if run from Bash, but doesn't seem to be doing so. If you give some more details about your development environment , I can take a closer look, but at the moment, I cannot reproduce the bug.

**Comment by yunwilliamyu** [comment]
Follow up: seems that Mac OS X doesn't work, but it did compile for the OP in Linux. Marking issue as closed, but with a comment that the code doesn't seem to compile in OS X.
