### ISSUE TITLE
num_batches option in wrapper fails to split training fasta file

### ISSUE THREAD

**Issue by nmb85** [yunwilliamyu/opal#2]
Hello Yun,

Lovely idea for Opal! I cannot use the wrapper because opal.py train will not split my training fasta file with ~5k bacterial genomes and paired taxids into batches. I can set --num-batches to 1000 and the wrapper continues to use a single batch. I looked at your train function and found this:
`for i in range(num_batches):
        seed = seed + 1
        batch_prefix = os.path.join(model_dir, "train.batch-{}".format(i))
        fasta_batch = batch_prefix + ".fasta"
        gi2taxid_batch = batch_prefix + ".gi2taxid"
        taxid_batch = batch_prefix + ".taxid"
`

But my run (`time ./opal.py train -c 10 -r --num-batches 1000 train/ model/`) is killed at this snippet, I guess because I run out of memory or something like that:

`print("Getting training set ...")
        sys.stdout.flush()
        skms = fasta2skm.main_generator(fasta2skm_namespace)
        training_list = [line.rstrip('\n') for line in skms]
`
The wrapper only generates a single set of massive batch-0 files: like one 300Gb file of fasta frags!

I cannot see where between these two pieces of code the wrapper splits up the fasta training set. Am I mean to do that myself first? Does it expect me to split up my fasta file first? The example datasets don't look like that...

**Comment by yunwilliamyu** [comment]
Hi there!

Ah, I think we're using batches to mean something different than what you're expecting. The actual training data passed into Vowpal Wabbit is a collection of L-mer reads sampled from the fasta file you give it. Opal will sample enough L-mer reads to have whatever coverage level you specify with "-c".

The default coverage is 15, and the default num_batches=1, so Opal is trying to sample enough L-mers to cover your fasta sequences 15 times, and trying to pass that 300GB file into vw, which is probably causing an OOM error.

The preferred way to do what you're trying to do is to set the coverage to something much lower, i.e. to 0.1, and then set num_batches to 150, which will equal an effective coverage of 15 after all's said and done, but each "batch" will be 150th the size.

Let me know if that helps, or you run into any other problems!

Cheers,
William

**Comment by nmb85** [comment]
Hi Yun,

Thanks very much for that clarification. I'll try using the preferred way that you've outlined and get back to you.

Cheers,
Nathan

**Comment by nmb85** [comment]
A brill! It works! I'd just note for future users that if the model/ dir is not empty, then the wrapper will throw an error and stop.
